sdl.harvard.geoimage: # {group_id}.{name} from the knime.yml
  src:  D:\GitHub\knime-geoimage-extension\knime_extension # Local path to folder containing the extension files
  conda_env_path: C:\Users\lil928\.conda\envs\geospatial_env # Path to the local installed Python environment to use
  debug_mode: false # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform